server:
  port: 1111
spring:
  application:
    name: TRAIN-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://lokesh:Loki@myfirstcluster.gxv9p.mongodb.net/CaseStudy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
   
logging:
  level:
    main: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
    
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan:
  - main
  paths-to-match:
  - /**