
   
server:
  port: 2222
spring:
  application:
    name: ADMIN-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://lokesh:Loki@myfirstcluster.gxv9p.mongodb.net/CaseStudy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
    
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan:
  - main
  paths-to-match:
  - /**

